---
- name: Configure Pod1 vCUBE2 1000v Router
  hosts: cisco
  gather_facts: no
  connection: network_cli

  tasks:
    - name: Configure SIP and voice service settings
      ios_config:
        lines:
          - mode border-element
          - allow-connections sip to sip
          - address-hiding
        parents: voice service voip

    - name: Configure gateway settings
      ios_config:
        lines:
          - media-inactivity-criteria all
          - timer receive-rtcp 5
        parents: gateway

    - name: Configure voice class codec
      ios_config:
        lines:
          - codec preference 1 g711ulaw
          - codec preference 2 g729r8
        parents: voice class codec 1

    - name: Configure voice class server-group 1
      ios_config:
        lines:
          - ipv4 10.1.5.15
        parents: voice class server-group 1

    - name: Configure voice class server-group 2
      ios_config:
        lines:
          - ipv4 10.250.250.201
        parents: voice class server-group 2

    - name: Configure voice class e164-pattern-map 1
      ios_config:
        lines:
          - e164 511555[23]...
          - e164 555[23]...
        parents: voice class e164-pattern-map 1

    - name: Configure voice class e164-pattern-map 2
      ios_config:
        lines:
          - e164 +011
          - e164 +1[2-9]..[2-9]......
          - e164 +[2-9]..[2-9]......
          - e164 +911
        parents: voice class e164-pattern-map 2

    - name: Configure dial-peer voice 101 voip
      ios_config:
        lines:
          - description CUCM-Facing
          - session protocol sipv2
          - session server-group 1
          - destination e164-pattern-map 1
          - incoming called e164-pattern-map 2
          - voice-class codec 1
          - voice-class sip bind control source-interface Gi1
          - voice-class sip bind media source-interface Gi1
          - dtmf-relay rtp-nte
        parents: dial-peer voice 101 voip

    - name: Configure dial-peer voice 201 voip
      ios_config:
        lines:
          - description PSTN-Facing Inbound-Outbound
          - session protocol sipv2
          - session server-group 2
          - destination e164-pattern-map 2
          - incoming called e164-pattern-map 1
          - voice-class codec 1
          - voice-class sip bind control source-interface Gi2
          - voice-class sip bind media source-interface Gi2
          - dtmf-relay rtp-nte
        parents: dial-peer voice 201 voip

    - name: Configure redundancy settings
      ios_config:
        lines:
          - track 1 interface GigabitEthernet1 line-protocol
          - track 2 interface GigabitEthernet2 line-protocol
          - redundancy
          - application redundancy
          - group 1
          - name cube_b2b_ha_1
          - priority 125 failover threshold 75
          - timers delay 5 reload 60
          - control G3 protocol 1
          - data G3
          - track 1 shutdown
          - protocol 1
          - name cube_b2b_ha_1
          - authentication text sol_ha1
        parents: []

    - name: Configure interface GigabitEthernet1 redundancy
      ios_config:
        lines:
          - redundancy rii 102
          - redundancy group 1 ip 10.1.5.100 exclusive
        parents: interface GigabitEthernet1

    - name: Configure SIP UA settings
      ios_config:
        lines:
          - sip-ua
        parents: []
