--- 
- name: Configure Cisco 1000v Router
  hosts: cisco_router
  gather_facts: no
  connection: network_cli
  vars:
    ansible_network_os: ios
    ansible_user: admin
    ansible_password: admin
    ansible_host: 10.1.5.12

  tasks:
    - name: Configure voice class codec
      ios_config:
        lines:
          - codec preference 1 g711ulaw
          - codec preference 2 g729r8
        parents: voice class codec 1

    - name: Configure voice class server-group 1
      ios_config:
        lines:
          - ipv4 10.1.5.15
        parents: voice class server-group 1

    - name: Configure voice class server-group 2
      ios_config:
        lines:
          - ipv4 10.250.250.201
        parents: voice class server-group 2

    - name: Configure voice class e164-pattern-map 1
      ios_config:
        lines:
          - e164 511555[23]?
        parents: voice class e164-pattern-map 1

    - name: Configure voice class e164-pattern-map 2
      ios_config:
        lines:
          - e164 011T
          - e164 911
          - e164 1[2-9]..[2-9]......
          - e164 [2-9]..[2-9]......
        parents: voice class e164-pattern-map 2

    - name: Configure dial-peer voice 101 voip
      ios_config:
        lines:
          - description CUCM
          - incoming called e164-pattern-map 2
          - session protocol sipv2
          - session server-group 1
          - destination e164-pattern-map 1
          - voice-class codec 1
          - dtmf-relay rtp-nte
          - voice-class sip bind control source-interface Gi0/0
          - voice-class sip bind media source-interface Gi0/0
        parents: dial-peer voice 101 voip

    - name: Configure dial-peer voice 201 voip
      ios_config:
        lines:
          - description PSTN
          - incoming called e164-pattern-map 1
          - session protocol sipv2
          - session server-group 2
          - destination e164-pattern-map 2
          - voice-class codec 1
          - dtmf-relay rtp-nte
          - voice-class sip bind control source-interface Gi0/1
          - voice-class sip bind media source-interface Gi0/1
        parents: dial-peer voice 201 voip
